name: Publish

on:
  push:
    tags: ["v*"]

jobs:
  publish:
    name: 发布到 NPM
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for OIDC
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          package-manager-cache: false
          registry-url: https://registry.npmjs.org

      - run: npm ci

      - run: npm run build --if-present

      - run: npm test

      - name: 发布
        run: npm publish
